return {
  { "bufferline.nvim", enabled = false },
  { "flash.nvim", enabled = false },
  { "grug-far.nvim", enabled = false },
  { "persistence.nvim", enabled = false },
  { "folke/trouble.nvim", enabled = false },
  { "CopilotChat.nvim", enabled = false },
  { "mini/surround.nvim", enabled = false },
  { "neogen", enabled = false },
  { "aerial.nvim", enabled = false },
  { "dial.nvim", enabled = false },
  { "leap.nvim", enabled = false },
  { "outline.nvim", enabled = false },
  { "overseer.nvim", enabled = false },
  { "refactoring.nvim", enabled = false },
  { "nvim-ansible", enabled = false },
  { "markdown-preview.nvim", enabled = false },
  { "nvim-dap-python", enabled = false },
  { "venv-selector", enabled = false },
  { "vim-dadbod-ui", enabled = false },
  { "edgy.nvim", enabled = false },
  { "kulala.nvim", enabled = false },
  { "neo-tree.nvim", enabled = false },
  { "vim-dadbod", enabled = false },
}
